version: '3.8'

networks:
  traefik:
    external: false

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    environment:
      - TRAEFIK_LOG_LEVEL=INFO
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik-dashboard.${DOMAIN_NAME}`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_AUTH_USERS}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik-dashboard.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=traefik-dashboard.${DOMAIN_NAME}"
      - "traefik.http.routers.traefik-secure.service=api@internal"
  db:
    image: postgres:15-alpine
    restart: always
    networks:
      - traefik
    volumes:
      - ~/apps/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - POSTGRES_USER=${POSTGRES_ADMIN_USER}
      - POSTGRES_DB=maydayplumbing
    expose:
      - 5432
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - traefik
    depends_on:
      - db
      - traefik
    environment:
        - POSTGRES_HOST=db
        - POSTGRES_PORT=5432
        - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
        - POSTGRES_USER=${POSTGRES_ADMIN_USER}
        - POSTGRES_DB=maydayplumbing
        - HOUSECALLPRO_USERNAME=${HOUSECALLPRO_USERNAME}
        - HOUSECALLPRO_PASSWORD=${HOUSECALLPRO_PASSWORD}
        - SERVICE_CATEGORY=${SERVICE_CATEGORY}
        - DOMAIN=${DOMAIN}
        - CATEGORY_URI=${CATEGORY_URI}
        - SERVICES_URI=${SERVICES_URI}
        - CALENDAR_URI=${CALENDAR_URI}
        - GMAIL_USERNAME=${GMAIL_USERNAME}
        - GMAIL_PASSWORD=${GMAIL_PASSWORD}
        - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
        - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
    ports:
      - 8000:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mayday.entrypoints=http"
      - "traefik.http.routers.mayday.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.middlewares.mayday-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.mayday.middlewares=mayday-https-redirect"
      - "traefik.http.routers.mayday-secure.entrypoints=https"
      - "traefik.http.routers.mayday-secure.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.mayday-secure.tls=true"
      - "traefik.http.routers.mayday-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mayday-secure.service=mayday"
      - "traefik.http.services.mayday.loadbalancer.server.port=8000"
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - .git/
            - __pycache__/
            - "*.pyc"
            - node_modules/